use crate::config::Shell;
use indoc::indoc;

pub fn generate_hook(shell: Shell) -> String {
    match shell {
        Shell::Zsh => indoc! {r#"
            # Side Project Manager - generated by: spm init zsh
            function sp() {
                if [[ -n "$1" ]]; then 
                    spm "$@";
                    return
                fi

                local selected=$(spm pick)
                if [[ -n "$selected" ]]; then
                    cd "$selected"
                fi
            }
        "#}
        .to_string(),

        Shell::Bash => indoc! {r#"
            # Side Project Manager - generated by: spm init bash
            function sp() {
                if [[ -n "$1" ]]; then 
                    spm "$@";
                    return
                fi

                local selected=$(spm pick)
                if [[ -n "$selected" ]]; then
                    cd "$selected"
                fi
            }
        "#}
        .to_string(),

        Shell::Fish => indoc! {r#"
            # Side Project Manager - generated by: spm init fish
            function sp
                if test (count $argv) -gt 0
                    spm $argv
                    return
                end

                set selected (spm pick)
                if test -n "$selected"
                    cd "$selected"
                end
            end
        "#}
        .to_string(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_zsh_hook() {
        let hook = generate_hook(Shell::Zsh);
        assert!(hook.contains("function sp()"));
        assert!(hook.contains("cd \"$selected\""));
    }

    #[test]
    fn test_bash_hook() {
        let hook = generate_hook(Shell::Bash);
        assert!(hook.contains("function sp()"));
        assert!(hook.contains("spm init bash"));
    }

    #[test]
    fn test_fish_hook() {
        let hook = generate_hook(Shell::Fish);
        assert!(hook.contains("function sp"));
        assert!(hook.contains("set selected"));
        assert!(hook.contains("cd \"$selected\""));
    }
}
