use crate::{cli, config::Shell};
use indoc::{formatdoc, indoc};
use strum::IntoEnumIterator;

pub fn detect_shell() -> Option<Shell> {
    let shell = std::env::var("SHELL").ok()?;
    let shell_name = shell.rsplit('/').next().unwrap_or(shell.as_str());

    match shell_name {
        "zsh" => Some(Shell::Zsh),
        "bash" => Some(Shell::Bash),
        "fish" => Some(Shell::Fish),
        _ => None,
    }
}

pub fn generate_hook(shell: Shell) -> String {
    let commands: Vec<String> = cli::Command::iter().map(|c| c.to_string()).collect();
    let commands = commands.join("|");

    match shell {
        Shell::Zsh => formatdoc! {r#"
            # Side Project Manager - generated by: spm init zsh
            function spm() {{
                if [[ $# -eq 0 ]]; then
                    local dir=$(command spm pick)
                    if [[ -n "$dir" ]]; then
                        cd "$dir"
                    fi
                    return
                fi

                local cmd="$1"
                case "$cmd" in
                    {commands})
                        command spm "$@"
                        ;;
                    *)
                        local dir=$(command spm pick "$@")
                        if [[ -n "$dir" ]]; then
                            cd "$dir"
                        fi
                        ;;
                esac
            }}
        "#,
        commands = commands
        }
        .to_string(),

        Shell::Bash => formatdoc! {r#"
            # Side Project Manager - generated by: spm init bash
            function spm() {{
                if [[ $# -eq 0 ]]; then
                    local dir=$(command spm pick)
                    if [[ -n "$dir" ]]; then
                        cd "$dir"
                    fi
                    return
                fi

                local cmd="$1"
                case "$cmd" in
                    {commands})
                        command spm "$@"
                        ;;
                    *)
                        local dir=$(command spm pick "$@")
                        if [[ -n "$dir" ]]; then
                            cd "$dir"
                        fi
                        ;;
                esac
            }}
        "#,
        commands = commands
        }
        .to_string(),

        Shell::Fish => formatdoc! {r#"
            # Side Project Manager - generated by: spm init fish
            function spm --wraps spm
                set -l argc (builtin count $argv)

                if test $argc -eq 0
                    set -l dir (command spm pick)
                    and cd $dir
                    return
                end

                set -l cmd $argv[1]
                switch $cmd
                    case {commands}
                        command spm $argv
                    case '*'
                        set -l dir (command spm pick $argv)
                        and cd $dir
                end
            end
        "#,
        commands = commands.replace("|", " ")
        }
        .to_string(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_zsh_hook() {
        let hook = generate_hook(Shell::Zsh);
        assert!(hook.contains("function spm()"));
        assert!(hook.contains("command spm pick"));
        assert!(hook.contains("command spm pick \"$@\""));
        assert!(hook.contains("cd \"$dir\""));
    }

    #[test]
    fn test_bash_hook() {
        let hook = generate_hook(Shell::Bash);
        assert!(hook.contains("function spm()"));
        assert!(hook.contains("command spm pick"));
        assert!(hook.contains("command spm pick \"$@\""));
        assert!(hook.contains("cd \"$dir\""));
    }

    #[test]
    fn test_fish_hook() {
        let hook = generate_hook(Shell::Fish);
        assert!(hook.contains("function spm"));
        assert!(hook.contains("command spm pick"));
        assert!(hook.contains("command spm pick $argv"));
        assert!(hook.contains("cd $dir"));
    }

    #[test]
    fn test_detect_shell() {
        unsafe {
            std::env::set_var("SHELL", "/bin/zsh");
        }
        assert_eq!(detect_shell(), Some(Shell::Zsh));
        unsafe {
            std::env::set_var("SHELL", "/usr/local/bin/bash");
        }
        assert_eq!(detect_shell(), Some(Shell::Bash));
        unsafe {
            std::env::set_var("SHELL", "/opt/homebrew/bin/fish");
        }
        assert_eq!(detect_shell(), Some(Shell::Fish));
    }
}
